import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import localFont from 'next/font/local'

const inter =localFont({
  src: '../../public/fonts/Inter-VariableFont_slnt,wght.ttf',
  variable: '--font-inter',
  weight: '100 900',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
